name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
              - name: Install Poetry Action
                uses: snok/install-poetry@v1.4.1
            
            
